name: key_manage
description: "你的密码管理器"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+2
  path: ^1.9.0
  get: ^4.6.1
  encrypt: ^5.0.3
  fluttertoast: ^8.2.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
