name: Build Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, ios]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$HOME/flutter/bin" >> $GITHUB_PATH  # 添加 Flutter 到 PATH
          echo "Flutter path set to: $GITHUB_PATH"  # 确认添加的路径

      - name: Verify Flutter installation
        run: flutter --version  # 验证 Flutter 是否安装成功

      - name: Flutter pub get
        run: flutter pub get

      - name: Get version number
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build ${{ matrix.platform }} app
        run: |
          if [ "${{ matrix.platform }}" == "android" ]; then
            flutter build apk --release --build-name=${{ env.VERSION }}
          else
            flutter build ios --release --build-name=${{ env.VERSION }}
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-build
          path: |
            build/app/outputs/apk/release/app-release.apk
            build/ios/iphoneos/*.ipa
